### PR TITLE
update logos & bump version to 1.2

### PR DESCRIPTION
**Pull request by mbutterick**
Update web images & CSS to reflect new web theme

### CODE REVIEW

**Comment by mbutterick** [comment]
BTW this PR is independent of [other controversies](https://github.com/racket/racket-lang-org/pull/28). It simply updates the logo & toolbar on the current web pages to be more consistent with the new blog design. Here’s a sample build:

https://mbutterick.github.io/plt-web/rws/www/

**Comment by lexi-lambda** [comment]
Even at my most curmudgeonly, I don’t think I could find anything wrong with this change. :) As long as it works with the docs and pkgs sites, I’d say there’s no reason not to merge.

**Comment by mflatt** [comment]
Would it make sense to leave the old images and style files and give new names to the changed ones --- maybe by adding some version number to the end? That would avoid problems with caches and let different sites update at different paces, since various sites refer to assets at racket-lang.org.

**Comment by mbutterick** [comment]
> since various sites refer to assets at racket-lang.org 

Can you give me an example? It wouldn’t be a big deal to versionize those filenames, but traps for the unwary, etc.

**Comment by mbutterick** [comment]
I appended `-1-2` to the files I changed and updated the references in the templates. I introduced a `private/image-version` module that will change all the version suffixes at once. It doesn’t make sense, however, to make this depend on `info.rkt`, as the version number there might change in the future for reasons unrelated to the images.

The build has been updated: https://mbutterick.github.io/plt-web/rws/www/

**Comment by mbutterick** [comment]
> change all the version suffixes at once

(Meaning, change the version suffixes within the modules that refer to them in building paths. The version suffixes on the images themselves would need to be changed manually to match.)

**Comment by mflatt** [comment]
Thanks! It looks like the old files are still changed in the PR's commit, but that seems easy enough to fix when we merge, unless I misunderstand.

**Comment by mbutterick** [comment]
I just force-pushed a squash commit onto this branch to clean it up, so IIUC, it now should now only refer to the changed files.

**Comment by mbutterick** [comment]
PS In time it will probably make sense to migrate these assets to the newly established [`racket/visual-design`](https://github.com/racket/visual-design) repo. But that is a problem for another day.

**Pull request merged**
